export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CREATED = 'AUTH_CREATED';
export const SENDING_EMAIL_START = 'SENDING_EMAIL_START';
export const SENDING_EMAIL_SUCCESS = 'SENDING_EMAIL_SUCCESS';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const PROFILE_START = 'PROFILE_START';
export const PROFILE_LOAD = 'PROFILE_LOAD';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_FAIL';

export const PROJECTS_LOADING_START = 'PROJECTS_LOADING_START';
export const PROJECTS_LOADING_SUCCESS = 'PROJECTS_LOADING_SUCCESS';
export const PROJECTS_LOADING_FAIL = 'PROJECTS_LOADING_FAIL';
export const PROJECTS_REMOVE_DELETED = 'PROJECTS_REMOVE_DELETED';

export const PROJECT_START = 'PROJECT_START';
export const PROJECT_LOAD = 'PROJECT_LOAD';
export const PROJECT_SUCCESS = 'PROJECT_SUCCESS';
export const PROJECT_FAIL = 'PROJECT_FAIL';
export const PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS';

export const TASKS_LOADING_START = 'TASKS_LOADING_START';
export const TASKS_LOADING_SUCCESS = 'TASKS_LOADING_SUCCESS';
export const TASKS_LOADING_FAIL = 'TASKS_LOADING_FAIL';
export const TASKS_REMOVE_DELETED = 'TASKS_REMOVE_DELETED';

export const TASK_START = 'TASK_START';
export const TASK_LOAD = 'TASK_LOAD';
export const TASK_SUCCESS = 'TASK_SUCCESS';
export const TASK_FAIL = 'TASK_FAIL';
export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS';